# Site settings
author: Nopasorn Kowathanakul
title: Nopasorn's Blog
header-img: img/home-bg.png
email: k.nopasorn@gmail.com
copyright_name: Nopasorn Kowathanakul
description: > # this means to ignore newlines until "baseurl:"
  A new journey of data science
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  knotmirai

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
